apiVersion: v1
kind: Service
metadata:
  name: pubsub-app-service
  labels:
    app: pubsub-app-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30501
    protocol: TCP
    name: http
  selector:
    app: pubsub-app
